################################################################################
MLI_FILE		= cordova_plugin_screenshot.mli
## Name which will be used in -package with ocamlfind
LIB_NAME		= cordova-plugin-screenshot
################################################################################
